CREATE TABLE IF NOT EXISTS products (
    id uuid DEFAULT gen_random_uuid(),
    brand_name TEXT NOT NULL,
    category TEXT [],
    collection_slugs TEXT [],
    color TEXT NOT NULL,
    designer TEXT NOT NULL,
    details TEXT,
    gender TEXT [],
    grid_pic_url TEXT,
    main_pic_url TEXT,
    orig_pic_url TEXT,
    has_pic BOOLEAN,
    has_stock BOOLEAN,
    keywords TEXT [],
    midsole TEXT,
    name TEXT NOT NULL,
    nickname TEXT,
    release_date_unix INTEGER,
    release_year INTEGER,
    retail_price_cents INTEGER,
    silhouette TEXT,
    sizes DECIMAL [] NOT NULL,
    sku TEXT NOT NULL,
    slug TEXT,
    status TEXT,
    description TEXT,
    upper_material TEXT,
    PRIMARY KEY (id)
);